
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 14 12:39:37 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 18;
  public static final int MOD = 20;
  public static final int ELSE = 4;
  public static final int PLUS = 16;
  public static final int RBRACE = 25;
  public static final int THEN = 3;
  public static final int SEMI = 23;
  public static final int MINUSMINUS = 14;
  public static final int IF = 2;
  public static final int LBRACE = 24;
  public static final int MORE_THAN = 9;
  public static final int ID = 6;
  public static final int NUM = 5;
  public static final int EQUALS = 7;
  public static final int LESS_EQUALS_THAN = 12;
  public static final int EOF = 0;
  public static final int DIVIDE = 19;
  public static final int LESS_THAN = 10;
  public static final int MINUS = 17;
  public static final int PLUSPLUS = 13;
  public static final int error = 1;
  public static final int NOT_EQUALS = 8;
  public static final int ASSIGNMENT = 22;
  public static final int RPAR = 27;
  public static final int HUNDRED = 15;
  public static final int LPAR = 26;
  public static final int MORE_EQUALS_THAN = 11;
  public static final int UMINUS = 21;
}

